#!/bin/bash
# Build /opt/narge/lists/narge-wild.txt from the public Narge feed.
# Each entry becomes "*.domain" (blocks domain + subdomains), except:
#  - public suffixes (PSL) are dropped entirely (would block whole countries/platforms)
#  - general platforms keep exact-only blocking until the list PR removes them
set -euo pipefail
OUT=/opt/narge/lists/narge-wild.txt; TMP=$(mktemp)
FEED=https://raw.githubusercontent.com/dov-max/narge-spec/main/dist/narge.txt
EXACT_ONLY="wordpress.com over-blog.com canalblog.com angelfire.com free.fr fc2.com itch.io b-cdn.net pbwstatic.com fastpic.ru pixhost.to imagetwist.com uploadhouse.com filestube.com booru.org sankakucomplex.com scrolller.com zproxy.org"
PSL_FALLBACK="blog.br blogspot.com co.hu co.il co.in co.jp co.uk com.ar com.au com.br com.co com.es ne.jp org.uk"
curl -fsS --max-time 30 "$FEED" -o "$TMP.feed"
curl -fsS --max-time 30 https://publicsuffix.org/list/public_suffix_list.dat -o "$TMP.psl" || : > "$TMP.psl"
python3 - "$TMP.feed" "$TMP.psl" "$TMP" "$EXACT_ONLY" "$PSL_FALLBACK" <<'PY'
import sys
feed,pslf,out,exact,fb=sys.argv[1:]
psl=set(fb.split())
for l in open(pslf,errors='ignore'):
    l=l.strip()
    if l and not l.startswith('//'): psl.add(l.lstrip('*.!'))
exact=set(exact.split())
names=[l.strip().lower() for l in open(feed) if l.strip() and not l.lstrip().startswith('#')]
if len(names)<200 or 'pornhub.com' not in names: sys.exit('feed looks wrong: %d names'%len(names))
o=[]
for n in names:
    if n in psl: continue
    o.append(n if n in exact else '*.'+n)
open(out,'w').write('# generated by narge-sync.sh from %s\n'%'dist/narge.txt'+'\n'.join(o)+'\n')
PY
chmod 644 "$TMP"; mv "$TMP" "$OUT"; rm -f "$TMP.feed" "$TMP.psl"
